config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'submissions#index'

  resources :submissions do
    member do
      put "like", to: "submissions#upvote"
      put "dislike", to: "submissions#downvote"
      get "userposts", to: "submissions#userposts"
    end
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :submission
end

app/models/submission.rb
class Submission < ApplicationRecord
  acts_as_votable
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :submissions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # POST /comments
  # POST /comments.json
  def create
    @submission = Submission.find(params[:submission_id])
    @comment = @submission.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @submission, notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end



  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @submission = Submission.find(params[:submission_id])
    @comment = @submission.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @submission}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:submission_id, :body, :user_id)
    end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.order(cached_votes_total: :desc)
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = current_user.submissions.build
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = current_user.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @submission = Submission.find(params[:id])

    #assign upvote to current user
    @submission.upvote_by current_user
    redirect_to submissions_path
  end

  def downvote
    @submission = Submission.find(params[:id])

    #assign upvote to current user
    @submission.downvote_by current_user
    redirect_to :back
  end

  def userposts
    @user = User.find(params[:id])
    @submissions = @user.submissions
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
 <div class="comments-wrapper clearfix">
   <div class="null-left">
     <p>
       <small><%= comment.user.email %><strong> <%= time_ago_in_words(comment.created_at) %></strong> ago </small>
     </p>
     <p>
       <%= comment.body %>
     </p>
   </div>
 </div>
 <% if comment.user == current_user %>
   <%= link_to 'delete', [comment.submission, comment], method: :delete, data: {confirm: "Are you sure?"} %>
 <% end%>
<% end%>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :submission_id %>
    <%= form.number_field :submission_id, id: :comment_submission_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Submission</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.submission_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Hackernews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

  </head>

  <body>


    <div id="main" class="container">
      <header class="navbar navbar-default" role="navigation">

        <div id="logo" class="navbar-brand"><%= link_to "Hacker News", root_path %></div>
        <% if user_signed_in? %>
          <ul class="nav">
            <li class="nav-item">
              <%= link_to "submit", new_submission_path, class: "nav-link disabled" %>
            </li>
            <li class="nav-item">
              <%= link_to "account", edit_user_registration_path, class: "nav-link disabled" %>
            </li>
            <li class="nav-item">
              <%= link_to "logout", destroy_user_session_path, :method => :delete, class: "nav-link disabled" %>
            </li>
          </ul>

          <% else %>
            <ul class="nav">
              <li class="nav-item"><%= link_to "login", new_user_session_path, class: "nav-link disabled" %></li>
            </ul>
          <% end %>
      </header>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
      <% end %>

      <div id="container" class="center-block">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :submission_title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :submission_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<table>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr class="post">
        <td>
          <%= link_to like_submission_path(submission),  method: :put do %>
            <i class="fa fa-caret-up fa-lg " aria-hidden="true"></i>
          <% end %>

          <%= link_to submission.title, submission.url, class: "title" %>
          <%= link_to submission.user.email, userposts_submission_path(submission.user) %>

        </td>
        <tr class="post">
          <td> <p><%= submission.get_upvotes.size %> points by <%= submission.user.email %> <%= time_ago_in_words(submission.created_at) %> ago | <%= link_to "#{submission.comments.count} comments", submission %> </p></td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<div class="page-header">
  <h4>
    <%= link_to like_submission_path(@submission), method: :put do %>
    <i class="fa fa-caret-up fa-lg" aria-hidden="true"></i>
    <% end %>
    <%= @submission.title %>
  

  </h4>
  <p>
    <%= link_to "#{@submission.comments.count} comments", @submission %>
  </p>
  <br />

<%= simple_form_for [@submission, Comment.new] do |f| %>
<%= f.text_area :body, class: "form-control" %>
<br />
<%= f.submit "add comment" %>
<% end %>
<div id="comments">
  <%= render :partial => @submission.comments %>
</div>
</div>

app/views/submissions/userposts.html.erb
<table>
  <tbody>
    <% @submissions.each do |submission| %>
      <tr class="post">
        <td>
          <%= link_to like_submission_path(submission), method: :put do %>
            <i class="fa fa-caret-up fa-lg " aria-hidden="true"></i>
          <% end %>

          <%= link_to submission.title, submission.url, class: "title" %>
          <%= link_to submission.user.email, submission_path(submission), target: "_blank" %>

        </td>
        <tr class="post">
          <td> <p><%= submission.get_upvotes.size %> points by <%= submission.user.email %> <%= time_ago_in_words(submission.created_at) %> ago | <%= link_to "#{submission.comments.count} comments", submission %> </p></td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>